/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package clientermi;

/**
 *
 * @author JFredy23
 */
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;

import Interface.RMIDAO;
public class ClienteRMI extends javax.swing.JFrame {

    /**
     * Creates new form ClienteRMI
     */
    public ClienteRMI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldPantalla = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabelNumeroUno = new javax.swing.JLabel();
        jTextFieldPrimero = new javax.swing.JTextField();
        jLabelSegundoNumero = new javax.swing.JLabel();
        jTextFieldSegundo = new javax.swing.JTextField();
        JPanelOperaciones = new javax.swing.JPanel();
        jButtonDiv = new javax.swing.JButton();
        jButtonMultiplicacion = new javax.swing.JButton();
        jButtonSuma = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jTextFieldPantalla, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(3, 0, 0, 50));

        jLabelNumeroUno.setText("Ingresa el primer numero");
        jPanel3.add(jLabelNumeroUno);
        jPanel3.add(jTextFieldPrimero);

        jLabelSegundoNumero.setText("Ingresa el segundo numero");
        jPanel3.add(jLabelSegundoNumero);

        jTextFieldSegundo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSegundoActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldSegundo);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel1);

        JPanelOperaciones.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        jButtonDiv.setText("/");
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });
        JPanelOperaciones.add(jButtonDiv);

        jButtonMultiplicacion.setText("*");
        jButtonMultiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiplicacionActionPerformed(evt);
            }
        });
        JPanelOperaciones.add(jButtonMultiplicacion);

        jButtonSuma.setText("+");
        jButtonSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSumaActionPerformed(evt);
            }
        });
        JPanelOperaciones.add(jButtonSuma);

        jButton1.setText("-");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        JPanelOperaciones.add(jButton1);

        jPanel2.add(JPanelOperaciones);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSegundoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSegundoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSegundoActionPerformed

    private void jButtonSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSumaActionPerformed
        try{
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            RMIDAO interfaz = (RMIDAO) registro.lookup("RemotoRMI");
            double suma;
            suma=interfaz.sumar(Double.parseDouble(jTextFieldPrimero.getText()), Double.parseDouble(jTextFieldSegundo.getText()));
            jTextFieldPantalla.setText(String.valueOf(suma) );
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_jButtonSumaActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        try{
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            RMIDAO interfaz = (RMIDAO) registro.lookup("RemotoRMI");
            double division;
            division=interfaz.dividir(Double.parseDouble(jTextFieldPrimero.getText()) , Double.parseDouble(jTextFieldSegundo.getText()));
            jTextFieldPantalla.setText(String.valueOf(division) );
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButtonMultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiplicacionActionPerformed
        // TODO add your handling code here:
        try{
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            RMIDAO interfaz = (RMIDAO) registro.lookup("RemotoRMI");
            double mul;
            mul=interfaz.multiplicar(Double.parseDouble(jTextFieldPrimero.getText()) , Double.parseDouble(jTextFieldSegundo.getText()));
            jTextFieldPantalla.setText(String.valueOf(mul) );
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_jButtonMultiplicacionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            Registry registro=LocateRegistry.getRegistry("127.0.0.1",7777);
            RMIDAO interfaz = (RMIDAO) registro.lookup("RemotoRMI");
            double res;
            res=interfaz.restar(Double.parseDouble(jTextFieldPrimero.getText()) , Double.parseDouble(jTextFieldSegundo.getText()));
            jTextFieldPantalla.setText(String.valueOf(res) );
        }catch(Exception e){
            System.out.println(""+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteRMI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteRMI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanelOperaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonMultiplicacion;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JLabel jLabelNumeroUno;
    private javax.swing.JLabel jLabelSegundoNumero;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextFieldPantalla;
    private javax.swing.JTextField jTextFieldPrimero;
    private javax.swing.JTextField jTextFieldSegundo;
    // End of variables declaration//GEN-END:variables
}
